"""initial database setup

Revision ID: ddd93ca9d5e9
Revises:
Create Date: 2026-09-28 14:49:16.382557

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "ddd93ca9d5e9"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
